name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -c Release --self-contained false
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
         name:  RunCat
         path:  RunCat\bin\Release
        
